ProjectMonoLevel2/Project.MVC/Controllers/VehicleMakeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project.Service.DAL;
using Project.Service.Models;
using Project.Service.ViewModels;

namespace Project.MVC.Controllers
{
    public class VehicleMakeController : Controller
    {
        private const int PageSize = 4;
        private readonly VehicleService vehicleService; 
        public VehicleMakeController()
        {
            vehicleService = VehicleService.GetInstance();
        }

        // GET: VehicleMake
        public ActionResult Index(string searchBy, string searchString, int? page, string sortBy)
        {
            ViewBag.SortName = string.IsNullOrEmpty(sortBy) ? "Name desc" : "";
            ViewBag.SortAbrv = sortBy == "Abrv" ? "Abrv desc" : "Abrv";

            if (searchString == null)
            {
                return View(vehicleService.GetSearchSortVehicleMake("", "", page, PageSize, sortBy));
            }
            else
            {
                return View(vehicleService.GetSearchSortVehicleMake(searchBy, searchString, page, PageSize, sortBy));
            }   
        }

        // GET: VehicleMake/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleMakeViewModel vehicleMake = vehicleService.FindVehicleMakeById((Guid)id);
            if (vehicleMake == null)
            {
                return HttpNotFound();
            }
            return View(vehicleMake);
        }

        // GET: VehicleMake/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: VehicleMake/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VehicleMakeId,Name,Abrv")] VehicleMakeViewModel vehicleMakeView)
        {
            if (ModelState.IsValid)
            {
                vehicleService.CreateVehicleMake(vehicleMakeView);
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Krivo unesen maker");
            }
            return View(vehicleMakeView);
        }

        // GET: VehicleMake/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleMakeViewModel vehicleMake = vehicleService.FindVehicleMakeById((Guid)id);
            if (vehicleMake == null)
            {
                return HttpNotFound();
            }
            return View(vehicleMake);
        }

        // POST: VehicleMake/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VehicleMakeId,Name,Abrv")] VehicleMakeViewModel vehicleMakeView)
        {
            if (ModelState.IsValid)
            {
                vehicleService.UpdateVehicleMake(vehicleMakeView);
                return RedirectToAction("Index");
            }
            return View(vehicleMakeView);
        }

        // GET: VehicleMake/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleMakeViewModel vehicleMake = vehicleService.FindVehicleMakeById((Guid)id);
            if (vehicleMake == null)
            {
                return HttpNotFound();
            }
            return View(vehicleMake);
        }

        // POST: VehicleMake/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            vehicleService.DeleteVehicleMake(id);
            return RedirectToAction("Index");
        }
    }
}

ProjectMonoLevel2/Project.MVC/Views/VehicleMake/Create.cshtml
@model Project.Service.ViewModels.VehicleMakeViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>VehicleMake</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Abrv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Abrv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Abrv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjectMonoLevel2/Project.MVC/Views/VehicleMake/Delete.cshtml
@model Project.Service.ViewModels.VehicleMakeViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VehicleMake</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Abrv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Abrv)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProjectMonoLevel2/Project.MVC/Views/VehicleMake/Details.cshtml
@model Project.Service.ViewModels.VehicleMakeViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>VehicleMake</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Abrv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Abrv)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.VehicleMakeId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProjectMonoLevel2/Project.MVC/Views/VehicleMake/Edit.cshtml
@model Project.Service.ViewModels.VehicleMakeViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>VehicleMake</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VehicleMakeId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Abrv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Abrv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Abrv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjectMonoLevel2/Project.MVC/Views/VehicleMake/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<Project.Service.ViewModels.VehicleMakeViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Vehicle Makers</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
    @using (Html.BeginForm("Index","VehicleMake", FormMethod.Get))
    {
        <b>Search by:</b>
        @Html.RadioButton("searchBy", "Name", true) <text>Name</text>
        @Html.RadioButton("searchBy", "Abrv") <text>Abrv</text> <br />
        @Html.TextBox("searchString") <input type="submit" value="Search" />
    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Name","Index", new { sortBy = ViewBag.SortName, searchBy = Request.QueryString["searchBy"],
           searchString = Request.QueryString["searchString"]})
        </th>
        <th>
            @Html.ActionLink("Abrv", "Index", new{sortBy = ViewBag.SortAbrv, searchBy = Request.QueryString["searchBy"],
           searchString = Request.QueryString["searchString"]})
        </th>
        <th>Edit, Details and Delete</th>
    </tr>
@if (Model.Count() == 0)
{
    <tr>
        <td colspan="4">There are no searched parameters.</td>
    </tr>
}
else
{
    foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Abrv)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.VehicleMakeId }) |
                @Html.ActionLink("Details", "Details", new { id = item.VehicleMakeId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.VehicleMakeId })
            </td>
        </tr>
    }
}
</table>
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, searchBy = Request.QueryString["searchBy"],searchString = Request.QueryString["searchString"],
sortBy = Request["sortBy"]}),
    new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true, DisplayItemSliceAndTotal = true})