ProjectMonoLevel2/Project.MVC/Controllers/VehicleModelController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project.Service.DAL;
using Project.Service.Models;
using Project.Service.ViewModels;

namespace Project.MVC.Controllers
{
    public class VehicleModelController : Controller
    {
        private readonly VehicleService vehicleService;
        private const int PageSize = 4;

        public VehicleModelController()
        {
            vehicleService = VehicleService.GetInstance();
        }

        // GET: VehicleModel
        public ActionResult Index(string searchBy, string searchString, int? page, string sortBy)
        {
            ViewBag.SortMaker = string.IsNullOrEmpty(sortBy) ? "Maker desc" : "";
            ViewBag.SortModel = sortBy == "Model" ? "Model desc" : "Model";
            ViewBag.SortAbrv = sortBy == "Abrv" ? "Abrv desc" : "Abrv";
            
            if (searchString == null)
            {
                return View(vehicleService.GetSearchSortVehicleModel("","",page, PageSize, sortBy));
            }
            else
            {  
                return View(vehicleService.GetSearchSortVehicleModel(searchBy, searchString, page, PageSize, sortBy));
            }
        }

        // GET: VehicleModel/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleModelViewModel vehicleModel = vehicleService.FindVehicleModelById((Guid)id);
            if (vehicleModel == null)
            {
                return HttpNotFound();
            }
            return View(vehicleModel);
        }

        // GET: VehicleModel/Create
        public ActionResult Create()
        {         
            ViewBag.VehicleMakeId = new SelectList(vehicleService.GetVehicleMakes(), "VehicleMakeId", "Name");
            return View();
        }

        // POST: VehicleModel/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VehicleModelId,VehicleMakeId,Name,Abrv")] VehicleModelViewModel vehicleModelView)
        {
            if (ModelState.IsValid)
            {
                vehicleService.CreateVehicleModel(vehicleModelView);
                return RedirectToAction("Index");
            }

            ViewBag.VehicleMakeId = new SelectList(vehicleService.GetVehicleMakes(), "VehicleMakeId", "Name", vehicleModelView.VehicleMakeId);
            return View(vehicleModelView);
        }

        // GET: VehicleModel/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleModelViewModel vehicleModelView = vehicleService.FindVehicleModelById((Guid)id);
            if (vehicleModelView == null)
            {
                return HttpNotFound();
            }
            ViewBag.VehicleMakeId = new SelectList(vehicleService.GetVehicleMakes(), "VehicleMakeId", "Name", vehicleModelView.VehicleMakeId);
            return View(vehicleModelView);
        }

        // POST: VehicleModel/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VehicleModelId,VehicleMakeId,Name,Abrv")] VehicleModelViewModel vehicleModelView)
        {
            if (ModelState.IsValid)
            {
                vehicleService.UpdateVehicleModel(vehicleModelView);
                return RedirectToAction("Index");
            }
            ViewBag.VehicleMakeId = new SelectList(vehicleService.GetVehicleMakes(), "VehicleMakeId", "Name", vehicleModelView.VehicleMakeId);
            return View(vehicleModelView);
        }

        // GET: VehicleModel/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleModelViewModel vehicleModelView = vehicleService.FindVehicleModelById((Guid)id);
            if (vehicleModelView == null)
            {
                return HttpNotFound();
            }
            return View(vehicleModelView);
        }

        // POST: VehicleModel/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            vehicleService.DeleteVehicleModel((Guid)id);
            return RedirectToAction("Index");
        }

    }
}

ProjectMonoLevel2/Project.MVC/Views/VehicleModel/Create.cshtml
@model Project.Service.ViewModels.VehicleModelViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>VehicleModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.VehicleMakeId, "VehicleMake", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VehicleMakeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VehicleMakeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Abrv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Abrv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Abrv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjectMonoLevel2/Project.MVC/Views/VehicleModel/Delete.cshtml
@model Project.Service.ViewModels.VehicleModelViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VehicleModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            VehicleMake
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehicleMake.Name)
        </dd>

        <dt>
            VehicleModel
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Abrv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Abrv)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProjectMonoLevel2/Project.MVC/Views/VehicleModel/Details.cshtml
@model Project.Service.ViewModels.VehicleModelViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>VehicleModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            VehicleMake
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehicleMake.Name)
        </dd>

        <dt>
            VehicleModel
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Abrv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Abrv)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.VehicleModelId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProjectMonoLevel2/Project.MVC/Views/VehicleModel/Edit.cshtml
@model Project.Service.ViewModels.VehicleModelViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>VehicleModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VehicleModelId)

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleMakeId, "VehicleMakeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VehicleMakeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VehicleMakeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Abrv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Abrv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Abrv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjectMonoLevel2/Project.MVC/Views/VehicleModel/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<Project.Service.ViewModels.VehicleModelViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Vehicle Models</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
    @using (Html.BeginForm("Index", "VehicleModel", FormMethod.Get))
    {
        <b>Search by:</b>
        @Html.RadioButton("searchBy", "Maker", true) <text>Maker</text>
        @Html.RadioButton("searchBy", "Name" ) <text>Model</text>
        @Html.RadioButton("searchBy", "Abrv") <text>Abrv</text> <br />
        @Html.TextBox("searchString") <input type="submit" value="Search" />
    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Maker", "Index", new
               {
                   sortBy = ViewBag.SortMaker,
                   searchBy = Request.QueryString["searchBy"],
                   searchString = Request.QueryString["searchString"]
               })
        </th>
        <th>
            @Html.ActionLink("Model", "Index", new
               {
                   sortBy = ViewBag.SortModel,
                   searchBy = Request.QueryString["searchBy"],
                   searchString = Request.QueryString["searchString"]
               })
        </th>
        <th>
            @Html.ActionLink("Abrv", "Index", new
                {
                    sortBy = ViewBag.SortAbrv,
                    searchBy = Request.QueryString["searchBy"],
                    searchString = Request.QueryString["searchString"]
                })
        </th>
        <th></th>
    </tr>
@if (Model.Count() == 0)
{
        <tr>
            <td colspan="4">There are no searched parameters.</td>
        </tr>
}
else
{
    foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.VehicleMake.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Abrv)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.VehicleModelId }) |
            @Html.ActionLink("Details", "Details", new { id = item.VehicleModelId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.VehicleModelId })
        </td>
    </tr>
    }
}

</table>
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, searchBy = Request.QueryString["searchBy"], searchString = Request.QueryString["searchString"],
    sortBy = Request["sortBy"]}),
    new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true, DisplayItemSliceAndTotal = true })